### ISSUE TITLE
Question about KVStore's put vs put_bytes

### ISSUE THREAD

**Issue by eminence** [cloudflare/workers-rs#102] opened 2021-12-21 01:23 UTC
When trying to use KVStore's `put` to store bytes, I get this runtime error:

```rust
let kv = ctx.kv("UPLOAD")?;
kv.put("test", "test".as_bytes())?.execute().await?;
```

```
TypeError: KV put() accepts only strings, ArrayBuffers, ArrayBufferViews, and ReadableStreams as values.
```

Two bits of confusion on this:

* The signature for put is:

```rust
pub fn put<T: ToRawKvValue>(
    &self,
    name: &str,
    value: T
) -> Result<PutOptionsBuilder, KvError>;
```

And there is an `impl ToRawKvValue for [u8]`, so this code compiles.  But if this function doesn't support byte slices, then why does it accept them?

* Why can't `put` accept bytes?  Stated another way:  why is there both a `put()` and `put_bytes()` ?   

Thanks!

**Comment by nilslice** [comment] 2021-12-21 17:01
Sorry for the additional ping @zebp :) If you can shed some light here, it would be much appreciated!

**Comment by zebp** [comment] 2021-12-22 16:06
Hi @eminence.

> Why can't put accept bytes? Stated another way: why is there both a put() and put_bytes() ?

Put is intended for arbitrary data that can be serialized to a string and then put into the KV store. The `impl ToRawKvValue for [u8]` is a left over from [this pr](https://github.com/zebp/worker-kv/pull/3) and is unintentionally included in the library, so it'll be removed before the library is stabilized.

But in this specific case because of the lack of [trait specialization](https://rust-lang.github.io/rfcs/1210-impl-specialization.html) what's actually happening is that the `impl<T: Serialize> ToRawKvValue for T` impl is being used, creating a number array which isn't allowed by KV. Intended behavior for this is that the value `[116, 101, 115, 116]` would be written to the KV as a string, but due to a bug it isn't.

`put_bytes` is the intended way for users to write raw bytes to KV stores. In the future there will be `put_byte_stream` for streaming bytes and to implement the final type of value for `string | ArrayBuffer | ArrayBufferView | ReadableStream` accepted by the [put](https://github.com/cloudflare/workers-types/blob/master/overrides/kv.d.ts#L73) function.

**Comment by nilslice** [comment] 2022-01-14 20:11
Just a follow-up & to close this out:

> Edit: worker-kv 0.5.1 has been released fixing this

We plan on cutting a new release including all the latest `worker-kv` goodies by end of next week.

**Closed by nilslice** 2022-01-14 20:11 UTC
