### ISSUE TITLE
[Feature] email event on the worker-rs

### ISSUE THREAD

**Issue by uksarkar** [cloudflare/workers-rs#446] opened 2024-02-16 13:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I'm wondering if there is any way to handle the `email` routing events via `workers-rs`, I didn't find any events or structs related to `EmailMessage` into workers-rs. I'm unsure if I'm missing something or if is there any workaround for this.

**Comment by rikhuijzer** [comment] 2024-04-16 10:38
I think this issue is a duplicate of https://github.com/cloudflare/workers-rs/issues/274.

**Closed** 2024-04-16 15:02 UTC
